### ISSUE TITLE
misprint

### ISSUE THREAD

**Issue by cp287-zz** [odinblockchain/wiki#2]
I think that in the second paragraph of "VPS Remote wallet install" it is necessary to replace "download the latest version from the PIVX GitHub repository" by "download the latest version from the ODIN GitHub repository".

**Comment by Manbearpixel** [comment]
Hey thanks for reporting this error! Which specific page are you referring too?

**Comment by cp287-zz** [comment]
https://github.com/odinblockchain/wiki/wiki/ODIN-Masternode-Setup-Guide - this one.

**Comment by Manbearpixel** [comment]
Thanks for submitting this issue to our attention!
